# Generated by Django 5.1.3 on 2024-11-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='message',
            new_name='alert_message',
        ),
    ]
